name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        run: docker build -t hanna877/fastapi:latest -f backend/Dockerfile ./backend

      - name: Build Frontend Docker Image
        run: docker build -t hanna877/nextjs-frontend:latest -f frontend/Dockerfile ./frontend

      - name: Build Database Docker Image
        run: docker build -t hanna877/mysql-sakila:latest -f db/Dockerfile ./db

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Backend Docker Image
        run: docker push hanna877/fastapi:latest

      - name: Push Frontend Docker Image
        run: docker push hanna877/nextjs-frontend:latest

      - name: Push Database Docker Image
        run: docker push hanna877/mysql-sakila:latest
